# pandoc

name: Docs to html
# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'docs/projects.md'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: create output dir
        run: mkdir output
      - uses: docker://pandoc/core:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --css=styling.css
            --from=gfm
            --to=html
            --standalone
            --self-contained
            --output=output/projects.html
            docs/projects.md

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "<th>"
          replace: "<th class=\"yellow\">"
          include: "output/projects.html" 
      - uses: actions/upload-artifact@v3
        with:
          name: html
          path: output
